### ISSUE TITLE
Leading level1 header still not displayed

### ISSUE THREAD

**Issue by tarsius** [bdewey/org-ruby#24] opened 2012-04-16 18:00 UTC
Also see #5 (I don't have permissions to reopen).

On github's built-in wiki the title in the file is used as page title when using markdown. Using org-mode syntax the file name is used instead.

Home.md

```
# The title I want
```

Home.org

```
* The title I want
```

Using `Home.md` the title is `The title I want` using org-mode it is `Home`. `The title I want` is missing completely, it's not even shown as a second title.

I am not sure whether this is a bug in `org-ruby` or if this is specific to the github wiki.

**Comment by tarsius** [comment] 2012-04-16 18:28
I found a work-around.

Home.org

```
not a title but github wiki will use it as title

text text text

* a real title
```

but this is not very satisfying as I would like the first line to be a title in the real org-mode too. Currently I have to decide whether I want the github wiki or the elisp exporters to treat the first line as header.

**Comment by wallyqs** [comment] 2012-04-17 01:16
I have confirmed this.

Given a wiki like this:

![Editing](http://imgur.com/8bzyR.png)

The first headline will be removed from the contents on the output.

![Editing](http://imgur.com/3y6NH.png)

Also another workaround for solving this would be to add: `#+TITLE: The title I want` as the first line of the org-mode content. This way both emacs html output and github wiki will display the same contents:

![Editing](http://i.imgur.com/SGD0Z.png)

![Editing](http://i.imgur.com/9k8oT.png)

**Comment by tarsius** [comment] 2012-05-07 17:03
Both work-arounds stopped working.

**Comment by tarsius** [comment] 2012-05-07 17:30
Using Markdown it also appears not to be possible (anymore?) have a title from the page name, so maybe this isn't a bug in org-ruby after all.

**Comment by vivdev** [comment] 2012-05-23 11:41
I am facing this bug too, using markdown syntax. The first header never shows and instead is replaced by header string "Home"

**Comment by tarsius** [comment] 2012-05-23 13:47
Since this also affects markdown it is probably not a bug in org-ruby but in gollum, and we should report the bug there. Still it would be nice to hear the thoughts of the org-ruby maintainer on this first.

**Comment by tarsius** [comment] 2012-05-23 13:54
Someone just created an issue for gollum: https://github.com/github/gollum/issues/357

**Comment by wallyqs** [comment] 2012-05-23 16:20
I also agree that this looks like a bug in Gollum, and it looks like somebody has reported this over there. In the meantime I will keep this ticket open until a solution is found.

**Comment by wallyqs** [comment] 2012-07-08 07:43
Closing since it is not an org-ruby issue.

**Closed as completed by wallyqs** 2012-07-08 07:43 UTC
